"""add family members

Revision ID: 1316560b87e4
Revises: cb3e59213f00
Create Date: 2026-07-19 09:37:09.235574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1316560b87e4'
down_revision: Union[str, Sequence[str], None] = 'cb3e59213f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_user_id'))

    op.drop_table('family_members')
    # ### end Alembic commands ###
