"""add score snapshots

Revision ID: 51793fe181c3
Revises: 6ccc35fa3b4e
Create Date: 2026-07-19 20:15:21.796619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51793fe181c3'
down_revision: Union[str, Sequence[str], None] = '6ccc35fa3b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('assessed_areas', sa.Integer(), nullable=False),
    sa.Column('total_areas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_score_user_date')
    )
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_snapshots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_snapshots_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_score_snapshots_date'))

    op.drop_table('score_snapshots')
    # ### end Alembic commands ###
