"""add created_at to profile, daily_log, medication

Revision ID: 5a7a26e8267d
Revises: 51793fe181c3
Create Date: 2026-07-21 15:50:19.113355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7a26e8267d'
down_revision: Union[str, Sequence[str], None] = '51793fe181c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
