"""add daily briefings

Revision ID: 6ccc35fa3b4e
Revises: 1316560b87e4
Create Date: 2026-07-19 17:00:45.488766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccc35fa3b4e'
down_revision: Union[str, Sequence[str], None] = '1316560b87e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('score_at_generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_briefing_user_date')
    )
    with op.batch_alter_table('daily_briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_briefings_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_briefings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_briefings_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_briefings_date'))

    op.drop_table('daily_briefings')
    # ### end Alembic commands ###
